# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true

# Following
# https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
cache:
  - ccache

addons:
  apt:
    packages:
     - ccache
